### ISSUE TITLE
QDMA latency measurment (dmalat) for MM Engine

### ISSUE THREAD

**Issue by insoulity** [Xilinx/dma_ip_drivers#118]
Hi there, 

I have a question abut latency measurement for QDMA system.

https://github.com/Xilinx/dma_ip_drivers/blob/11747e09faf287c264ad5ccaf13ed26fb9e4593a/QDMA/linux-kernel/apps/dma-latency/dmalat.c#L158

The line marked in the link above seems to indicate this application (dmalat) may intend to measure the latency of only Stream Engine (and NOT MM Engine) although there are some cases that consider when q_mode = Q_MODE_MM.

Thus, I'd like to ask whether the application is designed to measure the latency of both Q_MODE_MM and Q_MODE_ST or not.

Thanks,
Yongkee

**Comment by hmaarrfk** [comment]
Xilinx has a policy not to respond to people using this website. You should ask your question on their forum.

**Comment by insoulity** [comment]
Thanks, I will post there then.
