### ISSUE TITLE
Potential erroneous freeing of resources in qdma_queue_start

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#15]
Hey sorry for posting so many issues

https://github.com/Xilinx/dma_ip_drivers/blob/8b8c70b697f049649d5fa99be9c6bc4302d89ac9/QDMA/linux-kernel/libqdma/libqdma_export.c#L1150-L1162

This statement goes to `free_resources` but "resources" are allocated below in the call to

https://github.com/Xilinx/dma_ip_drivers/blob/8b8c70b697f049649d5fa99be9c6bc4302d89ac9/QDMA/linux-kernel/libqdma/libqdma_export.c#L1182-L1183

It seems like it should just return immediately right???

Could be related to https://github.com/Xilinx/dma_ip_drivers/issues/13

**Comment by sujathabanoth-xlnx** [comment]
Issue addressed in 2019.2 driver release, hence closing it
