### ISSUE TITLE
Error on buffer too small in qdma_queue_list

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#16]
Is the return value of `qdma_queue_list` supposed to signify error if the buffer is too small?

https://github.com/Xilinx/dma_ip_drivers/blob/8b8c70b697f049649d5fa99be9c6bc4302d89ac9/QDMA/linux-kernel/libqdma/libqdma_export.c#L763-L766

Currently, the return value in the case of `handle_truncation` is a positive number (as cur is always greater than buf)

**Comment by sujathabanoth-xlnx** [comment]
Issue addressed in 2019.2 driver release, Hence closing the issue
