### ISSUE TITLE
invalid user buffer can cause incorrect error handling in qdma_queue_add

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#18]
https://github.com/Xilinx/dma_ip_drivers/blob/8b8c70b697f049649d5fa99be9c6bc4302d89ac9/QDMA/linux-kernel/libqdma/libqdma_export.c#L1054-L1079

`qdma_queue_add` seems to need to handle non-zero return values (both positive and negative) from `intr_legacy_setup`  

That said, if the user passes a null buffer, then this error handling is simply ignored and `rv` is assumed to be OK.

PS: while not document in the doc string, `intr_legacy_setup` seems to return 1 if 
```c
	req_irq = list_empty(&legacy_intr_q_list);
	rv = req_irq ? 0 : 1;
        [...]
        return rv;
```
is satisfied

**Comment by sujathabanoth-xlnx** [comment]
Issue fixed in 2019.2 driver release, Hence closing
