### ISSUE TITLE
dump_bar_reg doesn't check the return value of first call to snprintf

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#20]
https://github.com/Xilinx/dma_ip_drivers/blob/8b8c70b697f049649d5fa99be9c6bc4302d89ac9/QDMA/linux-kernel/libqdma/qdma_debugfs_dev.c#L167-L170

All other calls are checked. 

Furthermore, snprintf might have actually written more bytes than `len` by the time `len` is returned. 
in fact, it would have written `buf_len` amount of bytes.

**Comment by hmaarrfk** [comment]
Should this return a negative number to indicate failure?

**Comment by sujathabanoth-xlnx** [comment]
Issue addressed in 2019.2 driver version, hence closing it
