### ISSUE TITLE
Header file from >=6.x.x kernel are not supported

### ISSUE THREAD

**Issue by xiaguangbo** [Xilinx/dma_ip_drivers#219]
API changed

`
/home/debian/Downloads/dma_ip_drivers-master/XDMA/linux-kernel/xdma/libxdma.c:29
11:25: error: implicit declaration of function ‘pci_unmap_sg’; did you mean ‘pci
_unmap_rom’? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-W
implicit-function-declaration-Werror=implicit-function-declaration8;;]          
 2911 |                         pci_unmap_sg(xdev->pdev, sgt->sgl, sgt->nents,  
      |                         ^~~~~~~~~~~~                                    
      |                         pci_unmap_rom
`

`
/home/debian/Downloads/dma_ip_drivers-master/XDMA/linux-kernel/xdma/libxdma.c:41
94:14: error: implicit declaration of function ‘pci_set_dma_mask’; did you me  a
n ‘set_dma_mask’? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#in
dex-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]     
 4194 |         if (!pci_set_dma_mask(pdev, DMA_BIT_MASK(64))) {                
      |              ^~~~~~~~~~~~~~~~                                           
      |              set_dma_mask
`

`
/home/debian/Downloads/dma_ip_drivers-master/XDMA/linux-kernel/xdma/cdev_sgdma.c
:108:17: error: too many arguments to function ‘caio->iocb->ki_complete’        
  108 |                 caio->iocb->ki_complete(caio->iocb, res, res2);         
      |                 ^~~~
`

**Comment by averybadplant** [comment]
Look for recent pull requests, there is some patches to support recent linux kernels.

**Comment by cyyself** [comment]
Consider try my branch at [https://github.com/cyyself/dma_ip_drivers/tree/fix-mainline](https://github.com/cyyself/dma_ip_drivers/tree/fix-mainline). I cherry-picked some patches from PR list and running on Linux v6.4 successfully.
