### ISSUE TITLE
LIBQDMA_VERSION macro gives invalid number

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#26]
https://github.com/Xilinx/dma_ip_drivers/blob/8b8c70b697f049649d5fa99be9c6bc4302d89ac9/QDMA/linux-kernel/libqdma/version.h#L28

With version 161 we have overrun the version numbering scheme.

**Comment by hmaarrfk** [comment]
This is the result
```
2018461 == 2018.3.161
```

though I expect you were targetting something like
```
20183161
```

**Comment by sujathabanoth-xlnx** [comment]
Issue fixed in latest driver releases
