### ISSUE TITLE
runtime error on ubuntu 18.04.2 LTS: ./qdma_run_stress_test.sh: line 302: echo: write error: Invalid argument

### ISSUE THREAD

**Issue by closertotheheart** [Xilinx/dma_ip_drivers#6]
root@super-poe:~/dma_ip_drivers/QDMA/linux-kernel/scripts# ./stress_test_top.sh 02000
#######################
#######################
make -C user clean;
make[1]: Entering directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/user'
make[1]: Leaving directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/user'
#######################
#######################
make -C tools clean;
make[1]: Entering directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/tools'
rm -rf *.o *.bin dma_to_device dma_from_device dma_from_device_w_udd dmautils
make[1]: Leaving directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/tools'
#######################
#######################
make[1]: Entering directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv'
srcdir = /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel.
KSRC = .
VF = .
EXTRA_FLAGS = .
ccflags-y = -D__GENL_REG_FAMILY_OPS_FUNC__ -D__READ_ONCE_DEFINED__.
make[1]: Leaving directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv'
"distro=, dmajor= dminor= "
4.15.184.15.0-47-generic: GIT,,, -DGITSP -DGIT
#######################
#######################
make -C user
make[1]: Entering directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/user'
cc -g -I. -I../include    -c -o cli/reg_cmd.o cli/reg_cmd.c
cc -g -I. -I../include    -c -o cli/cmd_parse.o cli/cmd_parse.c
cc -g -I. -I../include    -c -o cli/nl_user.o cli/nl_user.c
cc -g -I. -I../include    -c -o cli/main.o cli/main.c
cc cli/reg_cmd.o cli/cmd_parse.o cli/nl_user.o cli/main.o -o dmactl
make[1]: Leaving directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/user'
#######################
#######################
make -C tools
make[1]: Entering directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/tools'
cc -g -c -std=c99 -o dma_to_device.o dma_to_device.c -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE -D_AIO_AIX_SOURCE
cc -lrt -o dma_to_device dma_to_device.o -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE
cc -g -c -std=c99 -o dma_from_device.o dma_from_device.c -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE -D_AIO_AIX_SOURCE
cc -lrt -o dma_from_device dma_from_device.o -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE
cc -g -c -std=c99 -o dma_from_device_w_udd.o dma_from_device_w_udd.c -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE -D_AIO_AIX_SOURCE
cc -lrt -o dma_from_device_w_udd dma_from_device_w_udd.o -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE
cc -g -c -std=c99 -o dmautils.o dmautils.c -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE -D_AIO_AIX_SOURCE
cc -pthread -lrt -o dmautils dmautils.o -laio -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE
make[1]: Leaving directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/tools'
#######################
#######################
make[1]: Entering directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv'
srcdir = /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel.
KSRC = /lib/modules/4.15.0-47-generic/build.
VF = 0.
EXTRA_FLAGS = .
ccflags-y = -D__READ_ONCE_DEFINED__.
make[2]: Entering directory '/usr/src/linux-headers-4.15.0-47-generic'
srcdir = /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel.
KSRC = /lib/modules/4.15.0-47-generic/build.
VF = 0.
EXTRA_FLAGS = .
ccflags-y =  -D__READ_ONCE_DEFINED__.
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/nl.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/cdev.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma_mod.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_mbox.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_intr.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_st_c2h.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_thread.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/libqdma_export.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_device.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_sriov.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_descq.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_regs.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_debugfs_queue.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_debugfs.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_debugfs_dev.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_qconf_mgr.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/libqdma_config.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_context.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/xdev.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/thread.o
  LD [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma.o
  Building modules, stage 2.
srcdir = /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel.
KSRC = /lib/modules/4.15.0-47-generic/build.
VF = 0.
EXTRA_FLAGS = .
ccflags-y = -D__READ_ONCE_DEFINED__.
  MODPOST 1 modules
  CC      /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma.mod.o
  LD [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma.ko
make[2]: Leaving directory '/usr/src/linux-headers-4.15.0-47-generic'
make[1]: Leaving directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv'
#######################
#######################
make[1]: Entering directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv'
srcdir = /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel.
KSRC = /lib/modules/4.15.0-47-generic/build.
VF = 1.
EXTRA_FLAGS = -D__QDMA_VF__.
ccflags-y = -D__READ_ONCE_DEFINED__.
make[2]: Entering directory '/usr/src/linux-headers-4.15.0-47-generic'
srcdir = /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel.
KSRC = /lib/modules/4.15.0-47-generic/build.
VF = 1.
EXTRA_FLAGS = -D__QDMA_VF__.
ccflags-y =  -D__READ_ONCE_DEFINED__.
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma.mod.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/nl.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/cdev.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma_mod.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_mbox.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_intr.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_st_c2h.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_thread.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/libqdma_export.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_device.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_sriov.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_descq.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_debugfs_queue.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_debugfs.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_debugfs_dev.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_qconf_mgr.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/libqdma_config.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_context.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/xdev.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/thread.o
  CC [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/libqdma/qdma_regs.o
  LD [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma_vf.o
  Building modules, stage 2.
srcdir = /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel.
KSRC = /lib/modules/4.15.0-47-generic/build.
VF = 1.
EXTRA_FLAGS = -D__QDMA_VF__.
ccflags-y = -D__READ_ONCE_DEFINED__.
  MODPOST 1 modules
  CC      /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma_vf.mod.o
  LD [M]  /home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv/qdma_vf.ko
make[2]: Leaving directory '/usr/src/linux-headers-4.15.0-47-generic'
make[1]: Leaving directory '/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/drv'
"distro=, dmajor= dminor= "
4.15.184.15.0-47-generic: GIT,,, -DGITSP -DGIT
installing user tools to /usr/local/sbin ...
removed '/usr/local/sbin/dmactl'
'build/dmactl' -> '/usr/local/sbin/dmactl'
removed '/usr/local/sbin/dma_from_device'
'tools/dma_from_device' -> '/usr/local/sbin/dma_from_device'
removed '/usr/local/sbin/dma_to_device'
'tools/dma_to_device' -> '/usr/local/sbin/dma_to_device'
removed '/usr/local/sbin/dmautils'
'tools/dmautils' -> '/usr/local/sbin/dmautils'
MAN PAGES:
removed '/usr/share/man/man8/dmactl.8.gz'
'docs/dmactl.8.gz' -> '/usr/share/man/man8/dmactl.8.gz'
02000
qdma02000, 02:00.00, bar#2, reg 0xa0 -> 0x1, read back 0x1.
/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/scripts
/home/mcoyle/dma_ip_drivers/QDMA/linux-kernel/scripts
setting up environment
echo 2040 > /sys/bus/pci/devices/0000\:02\:00.0/qdma/qmax_vfs
echo 8 > /sys/bus/pci/devices/0000\:02\:00.0/sriov_numvfs
echo 4 > /sys/bus/pci/devices/0000\:02\:00.1/sriov_numvfs
echo 4 > /sys/bus/pci/devices/0000\:02\:00.2/sriov_numvfs
echo 4 > /sys/bus/pci/devices/0000\:02\:00.3/sriov_numvfs
./qdma_run_stress_test.sh: line 302: echo: write error: Invalid argument
./qdma_run_stress_test.sh: line 302: echo: write error: Invalid argument
./qdma_run_stress_test.sh: line 302: echo: write error: Invalid argument
./qdma_run_stress_test.sh: line 302: echo: write error: Invalid argument

./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn0/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn1/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn2/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn3/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn4/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn5/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn6/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.0/virtfn7/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.1/virtfn0/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.1/virtfn1/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.1/virtfn2/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.1/virtfn3/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.2/virtfn0/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.2/virtfn1/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.2/virtfn2/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.2/virtfn3/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.3/virtfn0/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.3/virtfn1/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.3/virtfn2/qdma/qmax: No such file or directory
./qdma_run_stress_test.sh: line 323: /sys/bus/pci/devices/0000:02:00.3/virtfn3/qdma/qmax: No such file or directory

qdma02000       0000:02:00.0    max QP: 2, 0~1
qdma02001       0000:02:00.1    max QP: 2, 2~3
qdma02002       0000:02:00.2    max QP: 2, 4~5
qdma02003       0000:02:00.3    max QP: 2, 6~7

setting up qdma02003-mm-101
transfer tests will run for 14400 secs
starting transfers
cmp: EOF on /tmp/out_mm02000_1 which is empty
cmp: /tmp/out_mm02000_3: No such file or directory
cmp: /tmp/out_mm02000_5: No such file or directory
cmp: /tmp/out_mm02000_7: No such file or directory
cmp: /tmp/out_mm02000_9: No such file or directory
cmp: /tmp/out_mm02000_11: No such file or directory
cmp: /tmp/out_mm02000_13: No such file or directory
cmp: /tmp/out_mm02000_15: No such file or directory
cmp: /tmp/out_mm02000_17: No such file or directory
cmp: /tmp/out_mm02000_19: No such file or directory
cmp: /tmp/out_mm02000_21: No such file or directory
cmp: /tmp/out_mm02000_23: No such file or directory
cmp: /tmp/out_mm02000_25: No such file or directory
cmp: /tmp/out_mm02000_27: No such file or directory
cmp: /tmp/out_mm02000_29: No such file or directory
cmp: /tmp/out_mm02000_31: No such file or directory
cmp: /tmp/out_mm02000_33: No such file or directory
cmp: /tmp/out_mm02000_35: No such file or directory
cmp: /tmp/out_mm02000_37: No such file or directory
cmp: /tmp/out_mm02000_39: No such file or directory
cmp: /tmp/out_mm02000_41: No such file or directory
cmp: /tmp/out_mm02000_43: No such file or directory
cmp: /tmp/out_mm02000_45: No such file or directory
cmp: /tmp/out_mm02000_47: No such file or directory
cmp: /tmp/out_mm02000_49: No such file or directory
cmp: /tmp/out_mm02000_51: No such file or directory
cmp: /tmp/out_mm02000_53: No such file or directory
cmp: /tmp/out_mm02000_55: No such file or directory
cmp: /tmp/out_mm02000_57: No such file or directory
cmp: /tmp/out_mm02000_59: No such file or directory
cmp: /tmp/out_mm02000_61: No such file or directory
cmp: /tmp/out_mm02000_63: No such file or directory
cmp: /tmp/out_mm02000_65: No such file or directory
cmp: /tmp/out_mm02000_67: No such file or directory
cmp: /tmp/out_mm02000_69: No such file or directory
cmp: /tmp/out_mm02000_71: No such file or directory
cmp: /tmp/out_mm02000_73: No such file or directory
cmp: /tmp/out_mm02000_75: No such file or directory
cmp: /tmp/out_mm02000_77: No such file or directory
cmp: /tmp/out_mm02000_79: No such file or directory
cmp: /tmp/out_mm02000_81: No such file or directory
cmp: /tmp/out_mm02000_83: No such file or directory
cmp: /tmp/out_mm02000_85: No such file or directory
cmp: /tmp/out_mm02000_87: No such file or directory
cmp: /tmp/out_mm02000_89: No such file or directory
cmp: /tmp/out_mm02000_91: No such file or directory
cmp: /tmp/out_mm02000_93: No such file or directory
cmp: /tmp/out_mm02000_95: No such file or directory
cmp: /tmp/out_mm02000_97: No such file or directory
cmp: /tmp/out_mm02000_99: No such file or directory
cmp: /tmp/out_mm02000_101: No such file or directory
cmp: EOF on /tmp/out_mm02001_1 which is empty
cmp: /tmp/out_mm02001_3: No such file or directory
cmp: /tmp/out_mm02001_5: No such file or directory
cmp: /tmp/out_mm02001_7: No such file or directory
cmp: /tmp/out_mm02001_9: No such file or directory
cmp: /tmp/out_mm02001_11: No such file or directory
cmp: /tmp/out_mm02001_13: No such file or directory
cmp: /tmp/out_mm02001_15: No such file or directory
cmp: /tmp/out_mm02001_17: No such file or directory
cmp: /tmp/out_mm02001_19: No such file or directory
cmp: /tmp/out_mm02001_21: No such file or directory
cmp: /tmp/out_mm02001_23: No such file or directory
cmp: /tmp/out_mm02001_25: No such file or directory
cmp: /tmp/out_mm02001_27: No such file or directory
cmp: /tmp/out_mm02001_29: No such file or directory
cmp: /tmp/out_mm02001_31: No such file or directory
cmp: /tmp/out_mm02001_33: No such file or directory
cmp: /tmp/out_mm02001_35: No such file or directory
cmp: /tmp/out_mm02001_37: No such file or directory
cmp: /tmp/out_mm02001_39: No such file or directory
cmp: /tmp/out_mm02001_41: No such file or directory
cmp: /tmp/out_mm02001_43: No such file or directory
cmp: /tmp/out_mm02001_45: No such file or directory
cmp: /tmp/out_mm02001_47: No such file or directory
cmp: /tmp/out_mm02001_49: No such file or directory
cmp: /tmp/out_mm02001_51: No such file or directory
cmp: /tmp/out_mm02001_53: No such file or directory
cmp: /tmp/out_mm02001_55: No such file or directory
cmp: /tmp/out_mm02001_57: No such file or directory
cmp: /tmp/out_mm02001_59: No such file or directory
cmp: /tmp/out_mm02001_61: No such file or directory
cmp: /tmp/out_mm02001_63: No such file or directory
cmp: /tmp/out_mm02001_65: No such file or directory
cmp: /tmp/out_mm02001_67: No such file or directory
cmp: /tmp/out_mm02001_69: No such file or directory
cmp: /tmp/out_mm02001_71: No such file or directory
cmp: /tmp/out_mm02001_73: No such file or directory
cmp: /tmp/out_mm02001_75: No such file or directory
cmp: /tmp/out_mm02001_77: No such file or directory
cmp: /tmp/out_mm02001_79: No such file or directory
cmp: /tmp/out_mm02001_81: No such file or directory
cmp: /tmp/out_mm02001_83: No such file or directory
cmp: /tmp/out_mm02001_85: No such file or directory
cmp: /tmp/out_mm02001_87: No such file or directory
cmp: /tmp/out_mm02001_89: No such file or directory
cmp: /tmp/out_mm02001_91: No such file or directory
cmp: /tmp/out_mm02001_93: No such file or directory
cmp: /tmp/out_mm02001_95: No such file or directory
cmp: /tmp/out_mm02001_97: No such file or directory
cmp: /tmp/out_mm02001_99: No such file or directory
cmp: /tmp/out_mm02001_101: No such file or directory
cmp: EOF on /tmp/out_mm02002_1 which is empty
cmp: /tmp/out_mm02002_3: No such file or directory
cmp: /tmp/out_mm02002_5: No such file or directory
cmp: /tmp/out_mm02002_7: No such file or directory
cmp: /tmp/out_mm02002_9: No such file or directory
cmp: /tmp/out_mm02002_11: No such file or directory
cmp: /tmp/out_mm02002_13: No such file or directory
cmp: /tmp/out_mm02002_15: No such file or directory
cmp: /tmp/out_mm02002_17: No such file or directory
cmp: /tmp/out_mm02002_19: No such file or directory
cmp: /tmp/out_mm02002_21: No such file or directory
cmp: /tmp/out_mm02002_23: No such file or directory
cmp: /tmp/out_mm02002_25: No such file or directory
cmp: /tmp/out_mm02002_27: No such file or directory
cmp: /tmp/out_mm02002_29: No such file or directory
cmp: /tmp/out_mm02002_31: No such file or directory
cmp: /tmp/out_mm02002_33: No such file or directory
cmp: /tmp/out_mm02002_35: No such file or directory
cmp: /tmp/out_mm02002_37: No such file or directory
cmp: /tmp/out_mm02002_39: No such file or directory
cmp: /tmp/out_mm02002_41: No such file or directory
cmp: /tmp/out_mm02002_43: No such file or directory
cmp: /tmp/out_mm02002_45: No such file or directory
cmp: /tmp/out_mm02002_47: No such file or directory
cmp: /tmp/out_mm02002_49: No such file or directory
cmp: /tmp/out_mm02002_51: No such file or directory
cmp: /tmp/out_mm02002_53: No such file or directory
cmp: /tmp/out_mm02002_55: No such file or directory
cmp: /tmp/out_mm02002_57: No such file or directory
cmp: /tmp/out_mm02002_59: No such file or directory
cmp: /tmp/out_mm02002_61: No such file or directory
cmp: /tmp/out_mm02002_63: No such file or directory
cmp: /tmp/out_mm02002_65: No such file or directory
cmp: /tmp/out_mm02002_67: No such file or directory
cmp: /tmp/out_mm02002_69: No such file or directory
cmp: /tmp/out_mm02002_71: No such file or directory
cmp: /tmp/out_mm02002_73: No such file or directory
cmp: /tmp/out_mm02002_75: No such file or directory
cmp: /tmp/out_mm02002_77: No such file or directory
cmp: /tmp/out_mm02002_79: No such file or directory
cmp: /tmp/out_mm02002_81: No such file or directory
cmp: /tmp/out_mm02002_83: No such file or directory
cmp: /tmp/out_mm02002_85: No such file or directory
cmp: /tmp/out_mm02002_87: No such file or directory
cmp: /tmp/out_mm02002_89: No such file or directory
cmp: /tmp/out_mm02002_91: No such file or directory
cmp: /tmp/out_mm02002_93: No such file or directory
cmp: /tmp/out_mm02002_95: No such file or directory
cmp: /tmp/out_mm02002_97: No such file or directory
cmp: /tmp/out_mm02002_99: No such file or directory
cmp: /tmp/out_mm02002_101: No such file or directory
cmp: EOF on /tmp/out_mm02003_1 which is empty
cmp: /tmp/out_mm02003_3: No such file or directory
cmp: /tmp/out_mm02003_5: No such file or directory
cmp: /tmp/out_mm02003_7: No such file or directory
cmp: /tmp/out_mm02003_9: No such file or directory
cmp: /tmp/out_mm02003_11: No such file or directory
cmp: /tmp/out_mm02003_13: No such file or directory
cmp: /tmp/out_mm02003_15: No such file or directory
cmp: /tmp/out_mm02003_17: No such file or directory
cmp: /tmp/out_mm02003_19: No such file or directory
cmp: /tmp/out_mm02003_21: No such file or directory
cmp: /tmp/out_mm02003_23: No such file or directory
cmp: /tmp/out_mm02003_25: No such file or directory
cmp: /tmp/out_mm02003_27: No such file or directory
cmp: /tmp/out_mm02003_29: No such file or directory
cmp: /tmp/out_mm02003_31: No such file or directory
cmp: /tmp/out_mm02003_33: No such file or directory
cmp: /tmp/out_mm02003_35: No such file or directory
cmp: /tmp/out_mm02003_37: No such file or directory
cmp: /tmp/out_mm02003_39: No such file or directory
cmp: /tmp/out_mm02003_41: No such file or directory
cmp: /tmp/out_mm02003_43: No such file or directory
cmp: /tmp/out_mm02003_45: No such file or directory
cmp: /tmp/out_mm02003_47: No such file or directory
cmp: /tmp/out_mm02003_49: No such file or directory
cmp: /tmp/out_mm02003_51: No such file or directory
cmp: /tmp/out_mm02003_53: No such file or directory
cmp: /tmp/out_mm02003_55: No such file or directory
cmp: /tmp/out_mm02003_57: No such file or directory
cmp: /tmp/out_mm02003_59: No such file or directory
cmp: /tmp/out_mm02003_61: No such file or directory
cmp: /tmp/out_mm02003_63: No such file or directory
cmp: /tmp/out_mm02003_65: No such file or directory
cmp: /tmp/out_mm02003_67: No such file or directory
cmp: /tmp/out_mm02003_69: No such file or directory
cmp: /tmp/out_mm02003_71: No such file or directory
cmp: /tmp/out_mm02003_73: No such file or directory
cmp: /tmp/out_mm02003_75: No such file or directory
cmp: /tmp/out_mm02003_77: No such file or directory
cmp: /tmp/out_mm02003_79: No such file or directory
cmp: /tmp/out_mm02003_81: No such file or directory
cmp: /tmp/out_mm02003_83: No such file or directory
cmp: /tmp/out_mm02003_85: No such file or directory
cmp: /tmp/out_mm02003_87: No such file or directory
cmp: /tmp/out_mm02003_89: No such file or directory
cmp: /tmp/out_mm02003_91: No such file or directory
cmp: /tmp/out_mm02003_93: No such file or directory
cmp: /tmp/out_mm02003_95: No such file or directory
cmp: /tmp/out_mm02003_97: No such file or directory
cmp: /tmp/out_mm02003_99: No such file or directory
cmp: /tmp/out_mm02003_101: No such file or directory

**Comment by hmaarrfk** [comment]
what is your output of `dmesg`. For me, `dmesg` shows that the kernel module isn't loaded with Error -16 EBUSY http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html

I wonder if it is tested on Ubuntu 18.04. They claim that the guest OS is Ubuntu 18.04, so I assume it works with it....

**Comment by sujathabanoth-xlnx** [comment]
stress_test_top.sh is no more available as a release artifact in latest driver package. It was tested in older driver package on Ubuntu 18.04 and it was working fine. Check the test environment.
Currently closing the issue
