### ISSUE TITLE
XDMA Changelog?

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#7]
I just noticed that you uploaded the XDMA Driver.
The one on AR65444 has a different version number.

Can you speak a little bit about the changes that were made? I've already noticed that one bug that I had found was fixed.

AR65444 has version 2017.1.47 while as of this post, the version number on XDMA is 2018.3.50

**Comment by karenx-xilinx** [comment]
Change log will be documented in RELEASE.
