### ISSUE TITLE
Change in license for application headers?

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#78]
Was it intentional to change the license text in the application headers?

I understand that GPL needs to be used for code that compiles with the kernel, but the application headers do not need to be.

Could we retain the dual license of the BSD/GPL for the libnl constants headers that we need to build up our applications with?

![image](https://user-images.githubusercontent.com/90008/93506035-ad7de980-f8e9-11ea-9adb-0c1ef8ab1cf1.png)

We've tried to use the `dma-ctl` application directly, but it is much too slow (since every invocation requires launching a new process).

We would prefer being able to continue to test, contribute, and work with Xilinx to improve their header in way that maintains the BSD license of the headers.

Thanks!

Mark

**Comment by sujathabanoth-xlnx** [comment]
Issue addressed in latest driver release, hence closing it

**Comment by hmaarrfk** [comment]
thanks
