### ISSUE TITLE
etc directory does not exist in XDMA

### ISSUE THREAD

**Issue by hmaarrfk** [Xilinx/dma_ip_drivers#9]
https://github.com/Xilinx/dma_ip_drivers/blob/8b8c70b697f049649d5fa99be9c6bc4302d89ac9/XDMA/linux-kernel/readme.txt#L18

While the etc directory is  referenced in the XDMA readme, it isn't in the repo.

I think it was dropped by the zip file https://www.xilinx.com/support/answers/65444.html during the 2018 release. It is available from the older release.

**Comment by karenx-xilinx** [comment]
reference to etc/ already removed in readme
